// Copyright (C) 2013 Brno University of Technology (http://nes.fit.vutbr.cz/ansa)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
/**
 * @file PimSplitter.h
 * @brief File contains implementation of PIMSplitter.
 * @date 3.12.2011
 * @author Veronika Rybova, Vladimir Vesely (mailto:ivesely@fit.vutbr.cz)
 * @details Splitter is common for all PIM modes. It is used to resent all PIM messages to
 *  correct PIM mode module. It also does work which is same for all modes, e.g.
 *  it send Hello messages and it manages table of PIM interfaces.
 */

#ifndef PIMSPLITTER_H_
#define PIMSPLITTER_H_

#include "networklayer/contract/IInterfaceTable.h"
#include "networklayer/common/InterfaceTableAccess.h"
#include "networklayer/contract/IRoutingTable.h"


#include <omnetpp.h>
#include "ansa/networklayer/pim/PIMPacket_m.h"
#include "ansa/networklayer/pim/PIMTimer_m.h"
#include "networklayer/contract/ipv4/IPv4ControlInfo.h"
#include "networklayer/ipv4/IPv4InterfaceData.h"
#include "networklayer/common/InterfaceTableAccess.h"
#include "ansa/networklayer/ipv4/AnsaRoutingTableAccess.h"
#include "networklayer/common/InterfaceTable.h"
#include "ansa/networklayer/ipv4/AnsaRoutingTable.h"
#include "base/NotificationBoard.h"
#include "common/NotifierConsts.h"
#include "ansa/util/InterfaceStateManager/InterfaceStateManager.h"
#include "ansa/networklayer/pim/tables/PimNeighborTable.h"
#include "ansa/networklayer/pim/tables/PimInterfaceTable.h"


#define HT 30.0										/**< Hello Timer = 30s. */

/**
 * @brief Class implements PIM Splitter, which splits PIM messages to correct PIM module.
 * @details This module is needed because we cannot distinguish PIM mode on layer 3, all of
 * them have same protocol number (103). PIM Splitter can resend PIM message to correct
 * PIM module according to configuration saved in PimInterfaceTable. Splitter also manages
 * PimNeighborTable.
 */
class PimSplitter : public cSimpleModule, protected INotifiable
{
	private:
		AnsaRoutingTable           	*rt;           	/**< Pointer to routing table. */
	    inet::IInterfaceTable         	*ift;          	/**< Pointer to interface table. */
	    NotificationBoard 			*nb; 		   	/**< Pointer to notification table. */

	    PimInterfaceTable			*pimIft;		/**< Pointer to table of PIM interfaces. */
	    PimNeighborTable			*pimNbt;		/**< Pointer to table of PIM neighbors. */

	    const char *				hostname;      	/**< Router hostname. */

	   void processPIMPkt(PIMPacket *pkt);
	   void processNLTimer(PIMTimer *timer);

	   // methods for Hello packets
	   PIMHello* createHelloPkt(int iftID);
	   void sendHelloPkt();
	   void processHelloPkt(PIMPacket *pkt);

	   // process notification
	   void receiveChangeNotification(int category, const cPolymorphic *details);
	   virtual void newMulticast(inet::IPv4Address destAddr, inet::IPv4Address srcAddr);
	   void igmpChange(inet::InterfaceEntry *interface);

	protected:
		virtual int numInitStages() const  {return 5;}
		virtual void handleMessage(cMessage *msg);
		virtual void initialize(int stage);

	public:
		PimSplitter(){};
};


#endif /* PIMSPLITTER_H_ */


/**
 * @mainpage Multicast Routing Modelling in OMNeT++ Documentation
 *
 * This is programming documentation to thesis Multicast Routing Modelling in OMNeT++ by Veronika Rybova.
 * In this documentation you can see whole C++ programming part of the thesis. You do not find here description
 * of NED files and classes which are autogenerated from files PIMTimer.msg and PIMPacket.msg. The reason is that
 * the output of these files is big amount of classes and documentation would be overwhelmed.
 *
 * The thesis is part of project ANSA, which takes place at the Faculty of Information Technology, Brno University
 * of Technology. For more information visit: https://nes.fit.vutbr.cz/ansa/pmwiki.php
 */
