INET Framework for OMNeT++/OMNEST: IPAddress.h File Reference
IPAddress.h File Reference
#include <omnetpp.h>
#include <iostream>
#include <string>
#include "INETDefs.h"
Classes
class IPAddress
Functions
std::ostream & operator<< (std::ostream &os, const IPAddress &ip)
void doPacking (cCommBuffer *buf, const IPAddress &addr)
void doUnpacking (cCommBuffer *buf, IPAddress &addr)
Variables
const short PORT_UNDEF = 0
const short PORT_MAX = 0x7fff
Function Documentation
void doPacking (cCommBuffer * buf, const IPAddress & addr) [inline]
Referenced by doPacking(), and TCPSegment::parsimPack().
{
    buf->pack(addr.getInt());
}
void doUnpacking (cCommBuffer * buf, IPAddress & addr) [inline]
Referenced by doUnpacking(), and TCPSegment::parsimUnpack().
{
    int32 d; buf->unpack(d); addr.set(d);
}
std::ostream& operator<< (std::ostream & os, const IPAddress & ip) [inline]
{
    return os << ip.str();
}
Variable Documentation
const short PORT_MAX = 0x7fff
const short PORT_UNDEF = 0
TCP/UDP port numbers
Referenced by RTPProfile::initialize(), RTCP::processIncomingRTCPPacket(), RTCP::processIncomingRTPPacket(), RTP::profileInitialized(), RTPInnerPacket::RTPInnerPacket(), RTPInterfacePacket::RTPInterfacePacket(), and RTPParticipantInfo::RTPParticipantInfo().