INET Framework for OMNeT++/OMNEST: Utils.cc File Reference
Utils.cc File Reference
#include "Utils.h"
#include "IntServ.h"
Functions
void removeDuplicates (std::vector< int > &vec)
int find (const EroVector &ERO, IPAddress node)
bool find (std::vector< int > &vec, int value)
bool find (const IPAddressVector &vec, IPAddress addr)
void append (std::vector< int > &dest, const std::vector< int > &src)
cModule * getPayloadOwner (cPacket *msg)
Function Documentation
void append (std::vector< int > & dest, const std::vector< int > & src)
TODO documentation
{
    for (unsigned int i = 0; i < src.size(); i++)
        dest.push_back(src[i]);
}
int find (const EroVector & ERO, IPAddress node)
TODO documentation
Referenced by TED::calculateShortestPath(), RTP::createProfile(), RTPProfile::createSenderModule(), RTPProfile::dataIn(), RoutingTable::deleteRoute(), RSVP::refreshResv(), Blackboard::registerClient(), SCTP::removeAssociation(), RoutingTable6::removeRoute(), FailureManager::replaceNode(), LinkStateRouting::sendToPeers(), NotificationBoard::subscribe(), Blackboard::subscribe(), and NotificationBoard::unsubscribe().
{
    for (unsigned int i = 0; i < ERO.size(); i++)
        if (ERO[i].node == node)
            return i;
    ASSERT(false);
    return -1; // to prevent warning
}
bool find (const IPAddressVector & vec, IPAddress addr)
TODO documentation
{
    for (unsigned int i = 0; i < vec.size(); i++)
        if (vec[i] == addr)
            return true;
    return false;
}
bool find (std::vector< int > & vec, int value)
TODO documentation
{
    for (unsigned int i = 0; i < vec.size(); i++)
        if (vec[i] == value)
            return true;
    return false;
}
cModule* getPayloadOwner (cPacket * msg)
XXX function appears to be unused
{
    while(msg->getEncapsulatedPacket())
        msg = msg->getEncapsulatedPacket();
    if (msg->hasPar("owner"))
        return simulation.getModule(msg->par("owner"));
    else
        return NULL;
}
void removeDuplicates (std::vector< int > & vec)
TODO documentation
{
    for (unsigned int i = 0; i < vec.size(); i++)
    {
        unsigned int j;
        for (j = 0; j < i; j++)
            if (vec[j] == vec[i])
                break;
        if (j < i)
        {
            vec.erase(vec.begin() + i);
            --i;
        }
    }
}