INET Framework for OMNeT++/OMNEST: InterfaceToken Class Reference
InterfaceToken Class Reference
#include <InterfaceToken.h>
Public Member Functions
InterfaceToken ()
InterfaceToken (uint32 low, uint32 normal, int len)
InterfaceToken (const InterfaceToken &t)
void operator= (const InterfaceToken &t)
int length () const
uint32 low () const
uint32 normal () const
Private Attributes
uint32 _normal
uint32 _low
short _len
Detailed Description
An "interface token" as defined in RFC 1971 (IPv6 Stateless Autoconfiguration). This class supports tokens of length 1..64-bits. An interface token needs to be provided by L2 modules in order to be able to form IPv6 link local addresses.
Definition at line 31 of file InterfaceToken.h.
Constructor & Destructor Documentation
InterfaceToken::InterfaceToken () [inline]
Definition at line 37 of file InterfaceToken.h.
{_normal=_low=_len=0;}
InterfaceToken::InterfaceToken (uint32 low, uint32 normal, int len) [inline]
Definition at line 38 of file InterfaceToken.h.
{_normal=normal; _low=low; _len=len;}
InterfaceToken::InterfaceToken (const InterfaceToken & t) [inline]
Definition at line 39 of file InterfaceToken.h.
{operator=(t);}
Member Function Documentation
int InterfaceToken::length () const [inline]
Definition at line 41 of file InterfaceToken.h.
Referenced by IPv6Address::formLinkLocalAddress().
{return _len;}
uint32 InterfaceToken::low () const [inline]
Definition at line 42 of file InterfaceToken.h.
Referenced by IPv6Address::formLinkLocalAddress().
{return _low;}
uint32 InterfaceToken::normal () const [inline]
Definition at line 43 of file InterfaceToken.h.
Referenced by IPv6Address::formLinkLocalAddress().
{return _normal;}
void InterfaceToken::operator= (const InterfaceToken & t) [inline]
Definition at line 40 of file InterfaceToken.h.
{_normal=t._normal; _low=t._low; _len=t._len;}
Member Data Documentation
short InterfaceToken::_len [private]
Definition at line 35 of file InterfaceToken.h.
Referenced by operator=().
uint32 InterfaceToken::_low [private]
Definition at line 34 of file InterfaceToken.h.
Referenced by operator=().
uint32 InterfaceToken::_normal [private]
Definition at line 34 of file InterfaceToken.h.
Referenced by operator=().
The documentation for this class was generated from the following file:
InterfaceToken.h