INET Framework for OMNeT++/OMNEST: OSPF::RoutingTableEntry Class Reference
OSPF::RoutingTableEntry Class Reference
#include <OSPFRoutingTableEntry.h>
Public Types
enum RoutingPathType { IntraArea = 0, InterArea = 1, Type1External = 2, Type2External = 3 }
typedef unsigned char RoutingDestinationType
Public Member Functions
RoutingTableEntry (void)
RoutingTableEntry (const RoutingTableEntry &entry)
virtual ~RoutingTableEntry (void)
bool operator== (const RoutingTableEntry &entry) const
bool operator!= (const RoutingTableEntry &entry) const
void SetDestinationType (RoutingDestinationType type)
RoutingDestinationType GetDestinationType (void) const
void SetDestinationID (IPAddress destID)
IPAddress GetDestinationID (void) const
void SetAddressMask (IPAddress destMask)
IPAddress GetAddressMask (void) const
void SetOptionalCapabilities (OSPFOptions options)
OSPFOptions GetOptionalCapabilities (void) const
void SetArea (AreaID source)
AreaID GetArea (void) const
void SetPathType (RoutingPathType type)
RoutingPathType GetPathType (void) const
void SetCost (Metric pathCost)
Metric GetCost (void) const
void SetType2Cost (Metric pathCost)
Metric GetType2Cost (void) const
void SetLinkStateOrigin (const OSPFLSA *lsa)
const OSPFLSA * GetLinkStateOrigin (void) const
void AddNextHop (NextHop hop)
void ClearNextHops (void)
unsigned int GetNextHopCount (void) const
NextHop GetNextHop (unsigned int index) const
Static Public Attributes
static const unsigned char NetworkDestination = 0
static const unsigned char AreaBorderRouterDestination = 1
static const unsigned char ASBoundaryRouterDestination = 2
Private Attributes
RoutingDestinationType destinationType
OSPFOptions optionalCapabilities
AreaID area
RoutingPathType pathType
Metric cost
Metric type2Cost
const OSPFLSA * linkStateOrigin
std::vector< NextHop > nextHops
Member Typedef Documentation
typedef unsigned char OSPF::RoutingTableEntry::RoutingDestinationType
Member Enumeration Documentation
enum OSPF::RoutingTableEntry::RoutingPathType
Enumerator:
IntraArea
InterArea
Type1External
Type2External
{
        IntraArea     = 0,
        InterArea     = 1,
        Type1External = 2,
        Type2External = 3
    };
Constructor & Destructor Documentation
OSPF::RoutingTableEntry::RoutingTableEntry (void) [inline]
                                                    :
    IPRoute(),
    destinationType(OSPF::RoutingTableEntry::NetworkDestination),
    area(OSPF::BackboneAreaID),
    pathType(OSPF::RoutingTableEntry::IntraArea),
    type2Cost(0),
    linkStateOrigin(NULL)
{
    netmask = 0xFFFFFFFF;
    source  = IPRoute::OSPF;
    memset(&optionalCapabilities, 0, sizeof(OSPFOptions));
}
OSPF::RoutingTableEntry::RoutingTableEntry (const RoutingTableEntry & entry) [inline]
                                                                              :
    destinationType(entry.destinationType),
    optionalCapabilities(entry.optionalCapabilities),
    area(entry.area),
    pathType(entry.pathType),
    cost(entry.cost),
    type2Cost(entry.type2Cost),
    linkStateOrigin(entry.linkStateOrigin),
    nextHops(entry.nextHops)
{
    host          = entry.host;
    netmask       = entry.netmask;
    gateway       = entry.gateway;
    interfacePtr  = entry.interfacePtr;
    type          = entry.type;
    source        = entry.source;
    metric        = entry.metric;
}
virtual OSPF::RoutingTableEntry::~RoutingTableEntry (void) [inline, virtual]
{}
Member Function Documentation
void OSPF::RoutingTableEntry::AddNextHop (OSPF::NextHop hop) [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateInterAreaRoutes(), OSPF::Area::CalculateShortestPathTree(), and OSPF::Area::ReCheckSummaryLSAs().
{
    if (nextHops.size() == 0) {
        InterfaceEntry*    routingInterface = InterfaceTableAccess().get()->getInterfaceById(hop.ifIndex);
        interfacePtr = routingInterface;
        //gateway = ULongFromIPv4Address(hop.hopAddress); // TODO: verify this isn't necessary
    }
    nextHops.push_back(hop);
}
void OSPF::RoutingTableEntry::ClearNextHops (void) [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateShortestPathTree(), and OSPF::Area::ReCheckSummaryLSAs().
{ nextHops.clear(); }
IPAddress OSPF::RoutingTableEntry::GetAddressMask (void) const [inline]
Referenced by OSPF::Area::CalculateInterAreaRoutes(), OSPF::Area::CalculateShortestPathTree(), OSPF::Router::Lookup(), operator<<(), and OSPF::Area::OriginateSummaryLSA().
{ return netmask; }
AreaID OSPF::RoutingTableEntry::GetArea (void) const [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateInterAreaRoutes(), operator<<(), OSPF::Router::PruneASBoundaryRouterEntries(), OSPF::Area::ReCheckSummaryLSAs(), and OSPF::Router::SelectLeastCostRoutingEntry().
{ return area; }
Metric OSPF::RoutingTableEntry::GetCost (void) const [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateInterAreaRoutes(), OSPF::Area::CalculateShortestPathTree(), OSPF::Area::FindSameOrWorseCostRoute(), operator<<(), OSPF::Area::ReCheckSummaryLSAs(), and OSPF::Router::SelectLeastCostRoutingEntry().
{ return cost; }
IPAddress OSPF::RoutingTableEntry::GetDestinationID (void) const [inline]
Referenced by OSPF::Area::CalculateInterAreaRoutes(), OSPF::Area::CalculateShortestPathTree(), OSPF::Area::FindSameOrWorseCostRoute(), OSPF::Router::GetRoutesToASBoundaryRouter(), OSPF::Router::HasRouteToASBoundaryRouter(), OSPF::Router::Lookup(), operator<<(), OSPF::Area::OriginateSummaryLSA(), and OSPF::Area::ReCheckSummaryLSAs().
{ return host; }
RoutingDestinationType OSPF::RoutingTableEntry::GetDestinationType (void) const [inline]
Referenced by OSPF::Area::CalculateInterAreaRoutes(), OSPF::Area::FindSameOrWorseCostRoute(), OSPF::Router::GetRoutesToASBoundaryRouter(), OSPF::Router::HasRouteToASBoundaryRouter(), OSPF::Router::Lookup(), operator<<(), OSPF::Area::OriginateSummaryLSA(), and OSPF::Area::ReCheckSummaryLSAs().
{ return destinationType; }
const OSPFLSA* OSPF::RoutingTableEntry::GetLinkStateOrigin (void) const [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateShortestPathTree(), and operator<<().
{ return linkStateOrigin; }
NextHop OSPF::RoutingTableEntry::GetNextHop (unsigned int index) const [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateInterAreaRoutes(), OSPF::Area::CreateRoutingTableEntryFromSummaryLSA(), operator<<(), and OSPF::Area::ReCheckSummaryLSAs().
{ return nextHops[index]; }
unsigned int OSPF::RoutingTableEntry::GetNextHopCount (void) const [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateInterAreaRoutes(), OSPF::Area::CreateRoutingTableEntryFromSummaryLSA(), operator<<(), and OSPF::Area::ReCheckSummaryLSAs().
{ return nextHops.size(); }
OSPFOptions OSPF::RoutingTableEntry::GetOptionalCapabilities (void) const [inline]
{ return optionalCapabilities; }
RoutingPathType OSPF::RoutingTableEntry::GetPathType (void) const [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateInterAreaRoutes(), OSPF::Area::FindSameOrWorseCostRoute(), OSPF::Router::GetPreferredEntry(), OSPF::Router::Lookup(), operator<<(), OSPF::Router::PruneASBoundaryRouterEntries(), and OSPF::Area::ReCheckSummaryLSAs().
{ return pathType; }
Metric OSPF::RoutingTableEntry::GetType2Cost (void) const [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), and operator<<().
{ return type2Cost; }
bool OSPF::RoutingTableEntry::operator!= (const RoutingTableEntry & entry) const [inline]
{ return (!((*this) == entry)); }
bool OSPF::RoutingTableEntry::operator== (const RoutingTableEntry & entry) const [inline]
{
    unsigned int hopCount = nextHops.size();
    unsigned int i        = 0;
    if (hopCount != entry.nextHops.size()) {
        return false;
    }
    for (i = 0; i < hopCount; i++) {
        if ((nextHops[i] != entry.nextHops[i]))
        {
            return false;
        }
    }
    return ((destinationType      == entry.destinationType)      &&
            (host                 == entry.host)                 &&
            (netmask              == entry.netmask)              &&
            (optionalCapabilities == entry.optionalCapabilities) &&
            (area                 == entry.area)                 &&
            (pathType             == entry.pathType)             &&
            (cost                 == entry.cost)                 &&
            (type2Cost            == entry.type2Cost)            &&
            (linkStateOrigin      == entry.linkStateOrigin));
}
void OSPF::RoutingTableEntry::SetAddressMask (IPAddress destMask) [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateShortestPathTree(), and OSPF::Router::Lookup().
{ netmask = destMask; }
void OSPF::RoutingTableEntry::SetArea (AreaID source) [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateShortestPathTree(), and OSPF::Router::Lookup().
{ area = source; }
void OSPF::RoutingTableEntry::SetCost (Metric pathCost) [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateShortestPathTree(), and OSPFRouting::LoadExternalRoute().
{
    cost = pathCost;
    // FIXME: this is a hack. But the correct way to do it is to implement a separate IRoutingTable module for OSPF...
    if (pathType == OSPF::RoutingTableEntry::Type2External) {
        metric = cost + type2Cost * 1000;
    } else {
        metric = cost;
    }
}
void OSPF::RoutingTableEntry::SetDestinationID (IPAddress destID) [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateShortestPathTree(), OSPF::Area::CreateRoutingTableEntryFromSummaryLSA(), and OSPF::Router::Lookup().
{ host = destID; }
void OSPF::RoutingTableEntry::SetDestinationType (RoutingDestinationType type) [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateShortestPathTree(), and OSPF::Router::Lookup().
{ destinationType = type; }
void OSPF::RoutingTableEntry::SetLinkStateOrigin (const OSPFLSA * lsa) [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), and OSPF::Area::CalculateShortestPathTree().
{ linkStateOrigin = lsa; }
void OSPF::RoutingTableEntry::SetOptionalCapabilities (OSPFOptions options) [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), and OSPF::Area::CalculateShortestPathTree().
{ optionalCapabilities = options; }
void OSPF::RoutingTableEntry::SetPathType (RoutingPathType type) [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateShortestPathTree(), OSPFRouting::LoadExternalRoute(), and OSPF::Router::Lookup().
{
    pathType = type;
    // FIXME: this is a hack. But the correct way to do it is to implement a separate IRoutingTable module for OSPF...
    if (pathType == OSPF::RoutingTableEntry::Type2External) {
        metric = cost + type2Cost * 1000;
    } else {
        metric = cost;
    }
}
void OSPF::RoutingTableEntry::SetType2Cost (Metric pathCost) [inline]
Referenced by OSPF::Router::CalculateASExternalRoutes(), and OSPFRouting::LoadExternalRoute().
{
    type2Cost = pathCost;
    // FIXME: this is a hack. But the correct way to do it is to implement a separate IRoutingTable module for OSPF...
    if (pathType == OSPF::RoutingTableEntry::Type2External) {
        metric = cost + type2Cost * 1000;
    } else {
        metric = cost;
    }
}
Member Data Documentation
AreaID OSPF::RoutingTableEntry::area [private]
Referenced by GetArea(), operator==(), and SetArea().
const unsigned char OSPF::RoutingTableEntry::AreaBorderRouterDestination = 1 [static]
Referenced by OSPF::Area::CalculateInterAreaRoutes(), OSPF::Area::CalculateShortestPathTree(), OSPF::Area::FindSameOrWorseCostRoute(), OSPF::Router::InstallASExternalLSA(), operator<<(), OSPF::Area::OriginateSummaryLSA(), and OSPF::Area::ReCheckSummaryLSAs().
const unsigned char OSPF::RoutingTableEntry::ASBoundaryRouterDestination = 2 [static]
Referenced by OSPF::Area::CalculateInterAreaRoutes(), OSPF::Area::CalculateShortestPathTree(), OSPF::Area::CreateRoutingTableEntryFromSummaryLSA(), OSPF::Area::FindSameOrWorseCostRoute(), OSPF::Router::GetRoutesToASBoundaryRouter(), OSPF::Router::HasRouteToASBoundaryRouter(), OSPF::Router::InstallASExternalLSA(), operator<<(), OSPF::Area::OriginateSummaryLSA(), and OSPF::Area::ReCheckSummaryLSAs().
Metric OSPF::RoutingTableEntry::cost [private]
Referenced by GetCost(), and operator==().
RoutingDestinationType OSPF::RoutingTableEntry::destinationType [private]
Referenced by GetDestinationType(), operator==(), and SetDestinationType().
const OSPFLSA* OSPF::RoutingTableEntry::linkStateOrigin [private]
Referenced by GetLinkStateOrigin(), operator==(), and SetLinkStateOrigin().
const unsigned char OSPF::RoutingTableEntry::NetworkDestination = 0 [static]
Referenced by OSPF::Router::CalculateASExternalRoutes(), OSPF::Area::CalculateInterAreaRoutes(), OSPF::Area::CalculateShortestPathTree(), OSPF::Area::CreateRoutingTableEntryFromSummaryLSA(), OSPF::Area::FindSameOrWorseCostRoute(), OSPF::Router::Lookup(), OSPF::Router::NotifyAboutRoutingTableChanges(), operator<<(), OSPF::Area::OriginateSummaryLSA(), OSPF::Router::RebuildRoutingTable(), and OSPF::Area::ReCheckSummaryLSAs().
std::vector<NextHop> OSPF::RoutingTableEntry::nextHops [private]
Referenced by ClearNextHops(), GetNextHop(), GetNextHopCount(), and operator==().
OSPFOptions OSPF::RoutingTableEntry::optionalCapabilities [private]
Referenced by GetOptionalCapabilities(), operator==(), RoutingTableEntry(), and SetOptionalCapabilities().
RoutingPathType OSPF::RoutingTableEntry::pathType [private]
Referenced by GetPathType(), and operator==().
Metric OSPF::RoutingTableEntry::type2Cost [private]
Referenced by GetType2Cost(), and operator==().
The documentation for this class was generated from the following file:
OSPFRoutingTableEntry.h