INET Framework for OMNeT++/OMNEST: OSPF::RouterLSA Class Reference
OSPF::RouterLSA Class Reference
#include <LSA.h>
Public Member Functions
RouterLSA (void)
RouterLSA (const OSPFRouterLSA &lsa)
RouterLSA (const RouterLSA &lsa)
virtual ~RouterLSA (void)
bool ValidateLSChecksum () const
bool Update (const OSPFRouterLSA *lsa)
bool DiffersFrom (const OSPFRouterLSA *routerLSA) const
Detailed Description
Definition at line 81 of file LSA.h.
Constructor & Destructor Documentation
OSPF::RouterLSA::RouterLSA (void) [inline]
Definition at line 86 of file LSA.h.
: OSPFRouterLSA(), RoutingInfo(), LSATrackingInfo() {}
OSPF::RouterLSA::RouterLSA (const OSPFRouterLSA & lsa) [inline]
Definition at line 87 of file LSA.h.
: OSPFRouterLSA(lsa), RoutingInfo(), LSATrackingInfo() {}
OSPF::RouterLSA::RouterLSA (const RouterLSA & lsa) [inline]
Definition at line 88 of file LSA.h.
: OSPFRouterLSA(lsa), RoutingInfo(lsa), LSATrackingInfo(lsa) {}
virtual OSPF::RouterLSA::~RouterLSA (void) [inline, virtual]
Definition at line 89 of file LSA.h.
{}
Member Function Documentation
bool OSPF::RouterLSA::DiffersFrom (const OSPFRouterLSA * routerLSA) const
Definition at line 33 of file RouterLSA.cc.
Referenced by Update().
{
    const OSPFLSAHeader& lsaHeader = routerLSA->getHeader();
    bool differentHeader = ((header_var.getLsOptions() != lsaHeader.getLsOptions()) ||
                            ((header_var.getLsAge() == MAX_AGE) && (lsaHeader.getLsAge() != MAX_AGE)) ||
                            ((header_var.getLsAge() != MAX_AGE) && (lsaHeader.getLsAge() == MAX_AGE)) ||
                            (header_var.getLsaLength() != lsaHeader.getLsaLength()));
    bool differentBody   = false;
    if (!differentHeader) {
        differentBody = ((V_VirtualLinkEndpoint_var != routerLSA->getV_VirtualLinkEndpoint()) ||
                         (E_ASBoundaryRouter_var != routerLSA->getE_ASBoundaryRouter()) ||
                         (B_AreaBorderRouter_var != routerLSA->getB_AreaBorderRouter()) ||
                         (numberOfLinks_var != routerLSA->getNumberOfLinks()) ||
                         (links_arraysize != routerLSA->getLinksArraySize()));
        if (!differentBody) {
            unsigned int linkCount = links_arraysize;
            for (unsigned int i = 0; i < linkCount; i++) {
                bool differentLink = ((links_var[i].getLinkID() != routerLSA->getLinks(i).getLinkID()) ||
                                      (links_var[i].getLinkData() != routerLSA->getLinks(i).getLinkData()) ||
                                      (links_var[i].getType() != routerLSA->getLinks(i).getType()) ||
                                      (links_var[i].getNumberOfTOS() != routerLSA->getLinks(i).getNumberOfTOS()) ||
                                      (links_var[i].getLinkCost() != routerLSA->getLinks(i).getLinkCost()) ||
                                      (links_var[i].getTosDataArraySize() != routerLSA->getLinks(i).getTosDataArraySize()));
                if (!differentLink) {
                    unsigned int tosCount = links_var[i].getTosDataArraySize();
                    for (unsigned int j = 0; j < tosCount; j++) {
                        bool differentTOS = ((links_var[i].getTosData(j).tos != routerLSA->getLinks(i).getTosData(j).tos) ||
                                             (links_var[i].getTosData(j).tosMetric[0] != routerLSA->getLinks(i).getTosData(j).tosMetric[0]) ||
                                             (links_var[i].getTosData(j).tosMetric[1] != routerLSA->getLinks(i).getTosData(j).tosMetric[1]) ||
                                             (links_var[i].getTosData(j).tosMetric[2] != routerLSA->getLinks(i).getTosData(j).tosMetric[2]));
                        if (differentTOS) {
                            differentLink = true;
                            break;
                        }
                    }
                }
                if (differentLink) {
                    differentBody = true;
                    break;
                }
            }
        }
    }
    return (differentHeader || differentBody);
}
bool OSPF::RouterLSA::Update (const OSPFRouterLSA * lsa)
Definition at line 20 of file RouterLSA.cc.
Referenced by OSPF::Area::AgeDatabase(), OSPF::NeighborState::ChangeState(), OSPF::InterfaceState::ChangeState(), and OSPF::HelloHandler::ProcessPacket().
{
    bool different = DiffersFrom(lsa);
    (*this) = (*lsa);
    ResetInstallTime();
    if (different) {
        ClearNextHops();
        return true;
    } else {
        return false;
    }
}
bool OSPF::RouterLSA::ValidateLSChecksum () const [inline]
Definition at line 91 of file LSA.h.
Referenced by OSPF::Area::AgeDatabase().
{ return true; } // not implemented
The documentation for this class was generated from the following files:
LSA.h
RouterLSA.cc