INET Framework for OMNeT++/OMNEST: TxNotifDetails Class Reference
TxNotifDetails Class Reference
#include <TxNotifDetails.h>
Public Member Functions
TxNotifDetails ()
cPacket * getPacket () const
InterfaceEntry * getInterfaceEntry () const
void setPacket (cPacket *m)
void setInterfaceEntry (InterfaceEntry *e)
Protected Attributes
cPacket * msg
InterfaceEntry * ie
Detailed Description
Details class for the NF_PP_TX_BEGIN, NF_PP_TX_END and NF_PP_RX_END notifications (normally triggered from PPP).
See also:
NotificationBoard
Definition at line 31 of file TxNotifDetails.h.
Constructor & Destructor Documentation
TxNotifDetails::TxNotifDetails () [inline]
Definition at line 38 of file TxNotifDetails.h.
{msg=NULL; ie=NULL;}
Member Function Documentation
InterfaceEntry* TxNotifDetails::getInterfaceEntry () const [inline]
Definition at line 41 of file TxNotifDetails.h.
Referenced by NAMTraceWriter::receiveChangeNotification().
{return ie;}
cPacket* TxNotifDetails::getPacket () const [inline]
Definition at line 40 of file TxNotifDetails.h.
Referenced by NAMTraceWriter::receiveChangeNotification().
{return msg;}
void TxNotifDetails::setInterfaceEntry (InterfaceEntry * e) [inline]
Definition at line 43 of file TxNotifDetails.h.
Referenced by PPP::initialize(), AnsaPPP::initialize(), EtherMACBase::initializeNotificationBoard(), and AnsaEtherMACBase::initializeNotificationBoard().
{ie = e;}
void TxNotifDetails::setPacket (cPacket * m) [inline]
Definition at line 42 of file TxNotifDetails.h.
Referenced by EtherMACBase::fireChangeNotification(), AnsaEtherMACBase::fireChangeNotification(), EtherMAC2::handleEndTxPeriod(), PPP::handleMessage(), AnsaPPP::handleMessage(), EtherMAC2::processMsgFromNetwork(), EtherMAC2::startFrameTransmission(), PPP::startTransmitting(), and AnsaPPP::startTransmitting().
{msg = m;}
Member Data Documentation
InterfaceEntry* TxNotifDetails::ie [protected]
Definition at line 35 of file TxNotifDetails.h.
Referenced by getInterfaceEntry(), setInterfaceEntry(), and TxNotifDetails().
cPacket* TxNotifDetails::msg [protected]
Definition at line 34 of file TxNotifDetails.h.
Referenced by getPacket(), setPacket(), and TxNotifDetails().
The documentation for this class was generated from the following file:
TxNotifDetails.h