INET Framework for OMNeT++/OMNEST: InterfaceProtocolData Class Reference
InterfaceProtocolData Class Reference
#include <InterfaceEntry.h>
Public Member Functions
InterfaceProtocolData ()
InterfaceEntry * getInterfaceEntry () const
Protected Member Functions
virtual void changed (int category)
Protected Attributes
InterfaceEntry * ownerp
Friends
class InterfaceEntry
Detailed Description
Base class for protocol-specific data on an interface. Notable subclasses are IPv4InterfaceData and IPv6InterfaceData.
Definition at line 41 of file InterfaceEntry.h.
Constructor & Destructor Documentation
InterfaceProtocolData::InterfaceProtocolData () [inline]
Definition at line 53 of file InterfaceEntry.h.
{ownerp = NULL;}
Member Function Documentation
void InterfaceProtocolData::changed (int category) [protected, virtual]
Definition at line 38 of file InterfaceEntry.cc.
Referenced by IPv4InterfaceData::changed1(), IPv6InterfaceData::changed1(), InterfaceEntry::configChanged(), and InterfaceEntry::stateChanged().
{
    // notify the containing InterfaceEntry that something changed
    if (ownerp)
        ownerp->changed(category);
}
InterfaceEntry* InterfaceProtocolData::getInterfaceEntry () const [inline]
Returns the InterfaceEntry that contains this data object, or NULL
Definition at line 58 of file InterfaceEntry.h.
{return ownerp;}
Friends And Related Function Documentation
friend class InterfaceEntry [friend]
Definition at line 43 of file InterfaceEntry.h.
Member Data Documentation
InterfaceEntry* InterfaceProtocolData::ownerp [protected]
Definition at line 46 of file InterfaceEntry.h.
Referenced by changed(), InterfaceEntry::getInterfaceTable(), InterfaceEntry::setInterfaceTable(), InterfaceEntry::setIPv4Data(), and InterfaceEntry::setIPv6Data().
The documentation for this class was generated from the following files:
InterfaceEntry.h
InterfaceEntry.cc