INET Framework for OMNeT++/OMNEST: TCPAlgorithm Class Reference
TCPAlgorithm Class Reference
#include <TCPAlgorithm.h>
Public Member Functions
TCPAlgorithm ()
virtual ~TCPAlgorithm ()
void setConnection (TCPConnection *_conn)
TCPStateVariables * getStateVariables ()
virtual void initialize ()
virtual void established (bool active)=0
virtual void connectionClosed ()=0
virtual void processTimer (cMessage *timer, TCPEventCode &event)=0
virtual void sendCommandInvoked ()=0
virtual void receivedOutOfOrderSegment ()=0
virtual void receiveSeqChanged ()=0
virtual void receivedDataAck (uint32 firstSeqAcked)=0
virtual void receivedDuplicateAck ()=0
virtual void receivedAckForDataNotYetSent (uint32 seq)=0
virtual void ackSent ()=0
virtual void dataSent (uint32 fromseq)=0
virtual void restartRexmitTimer ()=0
virtual void rttMeasurementCompleteUsingTS (uint32 echoedTS)=0
Protected Member Functions
virtual TCPStateVariables * createStateVariables ()=0
Protected Attributes
TCPConnection * conn
TCPStateVariables * state
Detailed Description
Abstract base class for TCP algorithms which encapsulate all behaviour during data transfer state: flavour of congestion control, fast retransmit/recovery, selective acknowledgement etc. Subclasses may implement various sets and flavours of the above algorithms.
Definition at line 34 of file TCPAlgorithm.h.
Constructor & Destructor Documentation
TCPAlgorithm::TCPAlgorithm () [inline]
Ctor.
Definition at line 52 of file TCPAlgorithm.h.
{state = NULL; conn = NULL;}
virtual TCPAlgorithm::~TCPAlgorithm () [inline, virtual]
Virtual dtor.
Definition at line 57 of file TCPAlgorithm.h.
{}
Member Function Documentation
virtual void TCPAlgorithm::ackSent () [pure virtual]
Called after we sent an ACK. This hook can be used to cancel the delayed-ACK timer.
Implemented in TCPBaseAlg, and DumbTCP.
Referenced by TCPConnection::retransmitOneSegment(), TCPConnection::sendAck(), TCPConnection::sendData(), TCPConnection::sendFin(), TCPConnection::sendOneNewSegment(), TCPConnection::sendProbe(), TCPConnection::sendRstAck(), TCPConnection::sendSegmentDuringLossRecoveryPhase(), and TCPConnection::sendSynAck().
virtual void TCPAlgorithm::connectionClosed () [pure virtual]
Called when the connection closes, it should cancel all running timers.
Implemented in TCPBaseAlg, and DumbTCP.
Referenced by TCPConnection::stateEntered().
virtual TCPStateVariables* TCPAlgorithm::createStateVariables () [protected, pure virtual]
Create state block (TCB) used by this TCP variant. It is expected that every TCPAlgorithm subclass will have its own state block, subclassed from TCPStateVariables. This factory method should create and return a "blank" state block of the appropriate type.
Implemented in DumbTCP, TCPNoCongestionControl, TCPTahoe, TCPNewReno, and TCPReno.
virtual void TCPAlgorithm::dataSent (uint32 fromseq) [pure virtual]
Called after we sent data. This hook can be used to schedule the retransmission timer, to start round-trip time measurement, etc. The argument is the seqno of the first byte sent.
Implemented in TCPBaseAlg, and DumbTCP.
Referenced by TCPConnection::sendData(), TCPConnection::sendOneNewSegment(), TCPConnection::sendProbe(), and TCPConnection::sendSegmentDuringLossRecoveryPhase().
virtual void TCPAlgorithm::established (bool active) [pure virtual]
Called when the connection is going to ESTABLISHED from SYN_SENT or SYN_RCVD. This is a place to initialize some variables (e.g. set cwnd to the MSS learned during connection setup). If we are on the active side, here we also have to finish the 3-way connection setup procedure by sending an ACK, possibly piggybacked on data.
Implemented in TCPBaseAlg, and DumbTCP.
Referenced by TCPConnection::processSegment1stThru8th(), and TCPConnection::processSegmentInSynSent().
TCPStateVariables* TCPAlgorithm::getStateVariables () [inline]
Creates and returns the TCP state variables.
Definition at line 68 of file TCPAlgorithm.h.
Referenced by TCPConnection::cloneListeningConnection(), and TCPConnection::initConnection().
{
        if (!state) state = createStateVariables();
        return state;
    }
virtual void TCPAlgorithm::initialize () [inline, virtual]
Should be redefined to initialize the object: create timers, etc. This method is necessary because the TCPConnection ptr is not available in the constructor yet.
Reimplemented in TCPBaseAlg, DumbTCP, and TCPNoCongestionControl.
Definition at line 78 of file TCPAlgorithm.h.
Referenced by TCPConnection::cloneListeningConnection(), and TCPConnection::initConnection().
{}
virtual void TCPAlgorithm::processTimer (cMessage * timer, TCPEventCode & event) [pure virtual]
Place to process timers specific to this TCPAlgorithm class. TCPConnection will invoke this method on any timer (self-message) it doesn't recognize (that is, any timer other than the 2MSL, CONN-ESTAB and FIN-WAIT-2 timers).
Method may also change the event code (by default set to TCP_E_IGNORE) to cause the state transition of TCP FSM.
Implemented in TCPBaseAlg, and DumbTCP.
Referenced by TCPConnection::processTimer().
virtual void TCPAlgorithm::receivedAckForDataNotYetSent (uint32 seq) [pure virtual]
Called after we received an ACK for data not yet sent. According to RFC 793 this function should send an ACK.
Implemented in TCPBaseAlg, and DumbTCP.
Referenced by TCPConnection::processAckInEstabEtc().
virtual void TCPAlgorithm::receivedDataAck (uint32 firstSeqAcked) [pure virtual]
Called after we received an ACK which acked some data (that is, we could advance snd_una). At this point the state variables (snd_una, snd_wnd) have already been updated. The argument firstSeqAcked is the previous snd_una value, that is, the number of bytes acked is (snd_una-firstSeqAcked). The dupack counter still reflects the old value (needed for Reno and NewReno); it'll be reset to 0 after this call returns.
Implemented in TCPBaseAlg, DumbTCP, TCPNoCongestionControl, TCPTahoe, TCPNewReno, and TCPReno.
Referenced by TCPConnection::processAckInEstabEtc(), and TCPConnection::processSegment1stThru8th().
virtual void TCPAlgorithm::receivedDuplicateAck () [pure virtual]
Called after we received a duplicate ACK (that is: ackNo==snd_una, no data in segment, segment doesn't carry window update, and also, we have unacked data). The dupack counter got already updated when calling this method (i.e. dupack==1 on first duplicate ACK.)
Implemented in TCPBaseAlg, DumbTCP, TCPTahoe, TCPNewReno, and TCPReno.
Referenced by TCPConnection::processAckInEstabEtc().
virtual void TCPAlgorithm::receivedOutOfOrderSegment () [pure virtual]
Called after receiving data which are in the window, but not at its left edge (seq!=rcv_nxt). This indicates that either segments got re-ordered in the way, or one segment was lost. RFC 1122 and RFC 2001 recommend sending an immediate ACK here (Fast Retransmit relies on that).
Implemented in TCPBaseAlg, and DumbTCP.
Referenced by TCPConnection::processSegment1stThru8th().
virtual void TCPAlgorithm::receiveSeqChanged () [pure virtual]
Called after rcv_nxt got advanced, either because we received in-sequence data ("text" in RFC 793 lingo) or a FIN. At this point, rcv_nxt has already been updated. This method should take care to send or schedule an ACK some time.
Implemented in TCPBaseAlg, and DumbTCP.
Referenced by TCPConnection::processSegment1stThru8th().
virtual void TCPAlgorithm::restartRexmitTimer () [pure virtual]
Restart REXMIT timer.
Implemented in TCPBaseAlg, and DumbTCP.
Referenced by TCPConnection::process_CLOSE(), TCPConnection::sendData(), and TCPConnection::sendSegmentDuringLossRecoveryPhase().
virtual void TCPAlgorithm::rttMeasurementCompleteUsingTS (uint32 echoedTS) [pure virtual]
Converting uint32 echoedTS to simtime_t and calling rttMeasurementComplete() to update state vars with new measured RTT value.
Implemented in TCPBaseAlg, and DumbTCP.
Referenced by TCPConnection::processAckInEstabEtc().
virtual void TCPAlgorithm::sendCommandInvoked () [pure virtual]
Called after user sent TCP_C_SEND command to us.
Implemented in TCPBaseAlg, and DumbTCP.
Referenced by TCPConnection::process_SEND().
void TCPAlgorithm::setConnection (TCPConnection * _conn) [inline]
Assign this object to a TCPConnection. Its sendQueue and receiveQueue must be set already at this time, because we cache their pointers here.
Definition at line 63 of file TCPAlgorithm.h.
Referenced by TCPConnection::cloneListeningConnection(), and TCPConnection::initConnection().
{conn = _conn;}
Member Data Documentation
TCPConnection* TCPAlgorithm::conn [protected]
Definition at line 37 of file TCPAlgorithm.h.
Referenced by DumbTCP::connectionClosed(), DumbTCP::dataSent(), DumbTCP::established(), TCPBaseAlg::established(), DumbTCP::initialize(), TCPBaseAlg::initialize(), TCPBaseAlg::processDelayedAckTimer(), TCPBaseAlg::processPersistTimer(), TCPNoCongestionControl::processRexmitTimer(), TCPNewReno::processRexmitTimer(), TCPReno::processRexmitTimer(), TCPTahoe::processRexmitTimer(), TCPBaseAlg::processRexmitTimer(), DumbTCP::processTimer(), DumbTCP::receivedAckForDataNotYetSent(), TCPBaseAlg::receivedAckForDataNotYetSent(), TCPReno::receivedDataAck(), TCPNewReno::receivedDataAck(), DumbTCP::receivedDataAck(), TCPBaseAlg::receivedDataAck(), TCPNewReno::receivedDuplicateAck(), TCPReno::receivedDuplicateAck(), TCPTahoe::receivedDuplicateAck(), TCPBaseAlg::receivedDuplicateAck(), DumbTCP::receivedOutOfOrderSegment(), TCPBaseAlg::receivedOutOfOrderSegment(), DumbTCP::receiveSeqChanged(), TCPBaseAlg::receiveSeqChanged(), TCPBaseAlg::rttMeasurementCompleteUsingTS(), DumbTCP::sendCommandInvoked(), TCPBaseAlg::sendData(), TCPBaseAlg::startRexmitTimer(), and DumbTCP::~DumbTCP().
TCPStateVariables* TCPAlgorithm::state [protected]
Reimplemented in TCPBaseAlg, TCPTahoeRenoFamily, DumbTCP, TCPNoCongestionControl, TCPNewReno, TCPReno, and TCPTahoe.
Definition at line 38 of file TCPAlgorithm.h.
The documentation for this class was generated from the following file:
TCPAlgorithm.h