INET Framework for OMNeT++/OMNEST: IPassiveQueue Class Reference
IPassiveQueue Class Reference
#include <IPassiveQueue.h>
Public Member Functions
virtual ~IPassiveQueue ()
virtual void requestPacket ()=0
Detailed Description
Abstract interface for passive queues.
Definition at line 28 of file IPassiveQueue.h.
Constructor & Destructor Documentation
virtual IPassiveQueue::~IPassiveQueue () [inline, virtual]
Definition at line 31 of file IPassiveQueue.h.
{}
Member Function Documentation
virtual void IPassiveQueue::requestPacket () [pure virtual]
The queue should send a packet whenever this method is invoked. If the queue is currently empty, it should send a packet when when one becomes available.
Implemented in PassiveQueueBase.
Referenced by EtherMACBase::beginSendFrames(), AnsaEtherMACBase::beginSendFrames(), PPP::handleMessage(), AnsaPPP::handleMessage(), PPP::initialize(), AnsaPPP::initialize(), EtherMACBase::initializeQueueModule(), AnsaEtherMACBase::initializeQueueModule(), Ieee80211Mac::initializeQueueModule(), and Ieee80211Mac::popTransmissionQueue().
The documentation for this class was generated from the following file:
IPassiveQueue.h