INET Framework for OMNeT++/OMNEST: SCTPAssociation::streamSchedulingFunctions Struct Reference
SCTPAssociation::streamSchedulingFunctions Struct Reference
#include <SCTPAssociation.h>
Public Attributes
void(SCTPAssociation::* ssInitStreams)(uint32 inStreams, uint32 outStreams)
int32(SCTPAssociation::* ssGetNextSid)(bool peek)
int32(SCTPAssociation::* ssUsableStreams)()
Detailed Description
Definition at line 794 of file SCTPAssociation.h.
Member Data Documentation
int32(SCTPAssociation::* SCTPAssociation::streamSchedulingFunctions::ssGetNextSid)(bool peek)
Definition at line 796 of file SCTPAssociation.h.
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), SCTPAssociation::nextChunkFitsIntoPacket(), SCTPAssociation::peekOutboundDataMsg(), and SCTPAssociation::SCTPAssociation().
void(SCTPAssociation::* SCTPAssociation::streamSchedulingFunctions::ssInitStreams)(uint32 inStreams, uint32 outStreams)
Definition at line 795 of file SCTPAssociation.h.
Referenced by SCTPAssociation::processInitAckArrived(), SCTPAssociation::SCTPAssociation(), and SCTPAssociation::sendInitAck().
int32(SCTPAssociation::* SCTPAssociation::streamSchedulingFunctions::ssUsableStreams)()
Definition at line 797 of file SCTPAssociation.h.
Referenced by SCTPAssociation::SCTPAssociation().
The documentation for this struct was generated from the following file:
SCTPAssociation.h