INET Framework for OMNeT++/OMNEST: SCTPAssociation::congestionControlFunctions Struct Reference
SCTPAssociation::congestionControlFunctions Struct Reference
Public Attributes
void(SCTPAssociation::* ccInitParams)(SCTPPathVariables *path)
void(SCTPAssociation::* ccUpdateAfterSack)()
void(SCTPAssociation::* ccUpdateAfterCwndTimeout)(SCTPPathVariables *path)
void(SCTPAssociation::* ccUpdateAfterRtxTimeout)(SCTPPathVariables *path)
void(SCTPAssociation::* ccUpdateMaxBurst)(SCTPPathVariables *path)
void(SCTPAssociation::* ccUpdateBytesAcked)(SCTPPathVariables *path, const uint32 ackedBytes, const bool ctsnaAdvanced)
Detailed Description
Definition at line 510 of file SCTPAssociation.h.
Member Data Documentation
void(SCTPAssociation::* SCTPAssociation::congestionControlFunctions::ccInitParams)(SCTPPathVariables *path)
Definition at line 511 of file SCTPAssociation.h.
Referenced by SCTPAssociation::stateEntered().
void(SCTPAssociation::* SCTPAssociation::congestionControlFunctions::ccUpdateAfterCwndTimeout)(SCTPPathVariables *path)
Definition at line 513 of file SCTPAssociation.h.
Referenced by SCTPAssociation::processTimer(), and SCTPAssociation::stateEntered().
void(SCTPAssociation::* SCTPAssociation::congestionControlFunctions::ccUpdateAfterRtxTimeout)(SCTPPathVariables *path)
Definition at line 514 of file SCTPAssociation.h.
Referenced by SCTPAssociation::process_TIMEOUT_RTX(), and SCTPAssociation::stateEntered().
void(SCTPAssociation::* SCTPAssociation::congestionControlFunctions::ccUpdateAfterSack)()
Definition at line 512 of file SCTPAssociation.h.
Referenced by SCTPAssociation::processSackArrived(), and SCTPAssociation::stateEntered().
void(SCTPAssociation::* SCTPAssociation::congestionControlFunctions::ccUpdateBytesAcked)(SCTPPathVariables *path, const uint32 ackedBytes, const bool ctsnaAdvanced)
Definition at line 516 of file SCTPAssociation.h.
Referenced by SCTPAssociation::processSackArrived(), and SCTPAssociation::stateEntered().
void(SCTPAssociation::* SCTPAssociation::congestionControlFunctions::ccUpdateMaxBurst)(SCTPPathVariables *path)
Definition at line 515 of file SCTPAssociation.h.
Referenced by SCTPAssociation::stateEntered().
The documentation for this struct was generated from the following file:
SCTPAssociation.h